export const UNAUTHORIZED_CAUSE = {
  ACCESS_TOKEN: {
    EXPIRED: 'EXPIRED_ACCESS_TOKEN',
    INVALID: 'INVALID_ACCESS_TOKEN'
  },
  REFRESH_TOKEN: {
    EXPIRED: 'EXPIRED_REFRESH_TOKEN',
    INVALID: 'INVALID_REFRESH_TOKEN'
  },
  INVALID: 'INVALID_TOKEN'
} as const
